'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const http=require('node:http');
const path=require('node:path');
const {createApplication}=require('../server.cjs');
const {createEntraAuthenticator}=require('../server/auth.cjs');

const principals={
  owner:{id:'demo-msp-oid',tenantId:'demo-tenant',name:'Morgan Reed',email:'morgan@northstar.example',role:'msp',appRole:'MSPPortal.Owner',companyId:null},
  operator:{id:'demo-msp-admin-oid',tenantId:'demo-tenant',name:'Maya Johnson',email:'maya@northstar.example',role:'msp',appRole:'MSPPortal.Admin',companyId:null},
  admin:{id:'demo-admin-oid',tenantId:'demo-tenant',name:'Taylor Morgan',email:'taylor@acme.example',role:'admin',appRole:'ClientPortal.Admin',companyId:'acme'},
  user:{id:'demo-user-oid',tenantId:'demo-tenant',name:'Jordan Taylor',email:'jordan@acme.example',role:'user',appRole:'ClientPortal.User',companyId:'acme'},
  wrongTenant:{id:'demo-user-oid',tenantId:'demo-tenant',name:'Jordan Taylor',email:'jordan@acme.example',role:'user',appRole:'ClientPortal.User',companyId:'atlas'},
  stranger:{id:'unknown-oid',tenantId:'demo-tenant',name:'Unknown User',email:'unknown@example.com',role:'user',appRole:'ClientPortal.User',companyId:'acme'}
};

let server,application,baseUrl;
test.before(async()=>{
  const config={production:false,demoMode:true,port:0,host:'127.0.0.1',trustProxy:false,staticRoot:path.join(__dirname,'..','dist'),sourceRoot:path.join(__dirname,'..'),databasePath:':memory:',seedDemoData:true,auth:{clientId:'test',tenantId:'demo-tenant',audience:'api://test',redirectUri:'http://127.0.0.1',apiScope:'api://test/Portal.Access',allowedClientId:'test'}};
  const authenticate=async req=>{const key=String(req.headers.authorization||'').replace(/^Bearer\s+/,'');const principal=principals[key];if(!principal){const error=new Error('A valid test identity is required.');error.status=401;error.code='AUTH_TOKEN_INVALID';error.expose=true;throw error}return principal};
  application=createApplication({config,authenticate});server=http.createServer(application.handler);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));baseUrl=`http://127.0.0.1:${server.address().port}`;
});
test.after(async()=>{await new Promise(resolve=>server.close(resolve));application.db.close()});

async function request(pathname,{as='user',method='GET',body=null}={}){const headers={Authorization:`Bearer ${as}`};const init={method,headers};if(body){headers['Content-Type']='application/json';init.body=JSON.stringify(body)}const response=await fetch(baseUrl+pathname,init);let parsed=null;try{parsed=await response.json()}catch{}return{response,body:parsed}}

test('health endpoint reports database and operational readiness without exposing paths or keys',async()=>{const{response,body}=await request('/api/health');assert.equal(response.status,200);assert.equal(body.database,'ready');assert.equal(body.operations.backupConfigured,false);assert.equal(body.operations.lastBackupAt,null);assert.equal(JSON.stringify(body).includes('databasePath'),false);assert.equal(JSON.stringify(body).includes('encryptionKey'),false)});
test('database-backed demo identities are local-only and disabled outside demo mode',async()=>{const demo=createEntraAuthenticator({demoMode:true});const owner=await demo({headers:{authorization:'Demo msp'},socket:{remoteAddress:'127.0.0.1'}});assert.equal(owner.appRole,'MSPPortal.Owner');const admin=await demo({headers:{authorization:'Demo admin'},socket:{remoteAddress:'::1'}});assert.equal(admin.companyId,'acme');await assert.rejects(()=>demo({headers:{authorization:'Demo user'},socket:{remoteAddress:'203.0.113.10'}}),error=>error.code==='AUTH_DEMO_LOCAL_ONLY');const production=createEntraAuthenticator({demoMode:false,tenantId:'tenant',clientId:'client'});await assert.rejects(()=>production({headers:{authorization:'Demo msp'},socket:{remoteAddress:'127.0.0.1'}}),error=>error.code==='AUTH_TOKEN_REQUIRED')});
test('client session is resolved from the provisioned membership',async()=>{const{response,body}=await request('/api/session',{as:'admin'});assert.equal(response.status,200);assert.equal(body.role,'admin');assert.equal(body.companyId,'cmp_acme');assert.equal(body.tenant.name,'Acme & Co.');assert.ok(body.entitlements.includes('billing'))});
test('client user lists only their assigned company',async()=>{const{response,body}=await request('/api/companies');assert.equal(response.status,200);assert.deepEqual(body.companies.map(company=>company.id),['cmp_acme'])});
test('client cannot read another company by guessed identifier',async()=>{const{response,body}=await request('/api/companies/cmp_atlas');assert.equal(response.status,404);assert.equal(body.error.code,'RESOURCE_NOT_FOUND')});
test('token company claim cannot create a membership',async()=>{const{response,body}=await request('/api/session',{as:'wrongTenant'});assert.equal(response.status,403);assert.equal(body.error.code,'TENANT_MEMBERSHIP_REQUIRED')});
test('unknown identity is denied instead of being created just in time',async()=>{const{response,body}=await request('/api/session',{as:'stranger'});assert.equal(response.status,403);assert.equal(body.error.code,'USER_NOT_PROVISIONED')});
test('assigned MSP administrator sees only the assigned portfolio',async()=>{const{response,body}=await request('/api/companies',{as:'operator'});assert.equal(response.status,200);assert.equal(body.companies.length,8);assert.equal(body.scope.kind,'assigned')});
test('assigned MSP administrator cannot read an unassigned client',async()=>{const{response}=await request('/api/companies/cmp_apex',{as:'operator'});assert.equal(response.status,404)});
test('MSP owner sees the complete client portfolio',async()=>{const{response,body}=await request('/api/companies',{as:'owner'});assert.equal(response.status,200);assert.equal(body.companies.length,24);assert.equal(body.scope.kind,'portfolio')});
test('people directory requires client administration permission',async()=>{const denied=await request('/api/companies/cmp_acme/people');assert.equal(denied.response.status,403);const allowed=await request('/api/companies/cmp_acme/people',{as:'admin'});assert.equal(allowed.response.status,200);assert.equal(allowed.body.people.length,2)});
test('integration metadata is MSP-only',async()=>{const denied=await request('/api/internal/integrations',{as:'admin'});assert.equal(denied.response.status,403);const allowed=await request('/api/internal/integrations',{as:'operator'});assert.equal(allowed.response.status,200);assert.equal(allowed.body.integrations.length,5)});
test('ConnectWise synchronization is MSP-only and reports configuration without exposing secrets',async()=>{const denied=await request('/api/internal/integrations/connectwise/sync',{as:'admin'});assert.equal(denied.response.status,403);const status=await request('/api/internal/integrations/connectwise/sync',{as:'operator'});assert.equal(status.response.status,200);assert.equal(status.body.configured,false);assert.equal(Object.hasOwn(status.body,'clientSecret'),false);const sync=await request('/api/internal/integrations/connectwise/sync',{as:'operator',method:'POST'});assert.equal(sync.response.status,503);assert.equal(sync.body.error.code,'CONNECTWISE_NOT_CONFIGURED');const runs=await request('/api/internal/integrations/connectwise/sync',{as:'operator'});assert.ok(runs.body.runs.some(run=>run.status==='failed'&&run.errorCode==='CONNECTWISE_NOT_CONFIGURED'))});
test('known route rejects unsupported methods',async()=>{const{response,body}=await request('/api/internal/integrations',{as:'owner',method:'POST'});assert.equal(response.status,405);assert.equal(response.headers.get('allow'),'GET, PUT');assert.equal(body.error.code,'METHOD_NOT_ALLOWED')});
test('unknown API route returns JSON 404 instead of the SPA',async()=>{const{response,body}=await request('/api/does-not-exist',{as:'owner'});assert.equal(response.status,404);assert.match(response.headers.get('content-type'),/application\/json/);assert.equal(body.error.code,'API_ROUTE_NOT_FOUND')});
test('server and configuration files are never exposed as static assets',async()=>{const{response,body}=await request('/server.cjs',{as:'owner'});assert.equal(response.status,404);assert.equal(body.error.code,'STATIC_ASSET_NOT_FOUND')});
test('authorization denials are written to the durable audit log',async()=>{const{response,body}=await request('/api/internal/audit?limit=100',{as:'owner'});assert.equal(response.status,200);assert.ok(body.events.some(event=>event.outcome==='denied'&&['RESOURCE_NOT_FOUND','PERMISSION_DENIED','TENANT_MEMBERSHIP_REQUIRED','USER_NOT_PROVISIONED'].includes(event.reasonCode)))});
test('portal-store script is served in source mode',async()=>{const response=await fetch(baseUrl+'/portal-store.js');assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/javascript/)});
test('portal-api script is served without stale development caching',async()=>{const response=await fetch(baseUrl+'/portal-api.js');assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/javascript/);assert.equal(response.headers.get('cache-control'),'no-cache')});
test('client user can create, update, and list company-scoped ticket records',async()=>{const created=await request('/api/companies/cmp_acme/records',{method:'POST',body:{id:'ticket-printer-queue',type:'ticket',title:'Printer queue stuck',status:'open',priority:'normal',payload:{board:'Service Desk',statusLabel:'New'}}});assert.equal(created.response.status,201);assert.equal(created.body.record.type,'ticket');const updated=await request('/api/companies/cmp_acme/records/ticket-printer-queue',{method:'PATCH',body:{status:'resolved',priority:'high',payload:{statusLabel:'Resolved',lastAction:'ticket-close'}}});assert.equal(updated.response.status,200);assert.equal(updated.body.record.status,'resolved');assert.equal(updated.body.record.payload.lastAction,'ticket-close');const listed=await request('/api/companies/cmp_acme/records?type=ticket');assert.equal(listed.response.status,200);assert.ok(listed.body.records.some(record=>record.title==='Printer queue stuck'&&record.status==='resolved'))});
test('client user cannot create privileged company records',async()=>{const denied=await request('/api/companies/cmp_acme/records',{method:'POST',body:{type:'asset',title:'Firewall',payload:{hostname:'fw01'}}});assert.equal(denied.response.status,403);assert.equal(denied.body.error.code,'PERMISSION_DENIED')});
test('client admin can update invoice payment state but end user cannot',async()=>{const created=await request('/api/companies/cmp_acme/records',{as:'admin',method:'POST',body:{id:'invoice-acme-0711',type:'invoice',title:'INV-2026-0711',status:'active',priority:'normal',payload:{invoice:'INV-2026-0711',amount:'$4,820.00',statusLabel:'Due Jul 15'}}});assert.equal(created.response.status,201);const denied=await request('/api/companies/cmp_acme/records/invoice-acme-0711',{method:'PATCH',body:{status:'paid',payload:{statusLabel:'Paid'}}});assert.equal(denied.response.status,403);const paid=await request('/api/companies/cmp_acme/records/invoice-acme-0711',{as:'admin',method:'PATCH',body:{status:'paid',payload:{statusLabel:'Paid',lastAction:'payment-submitted',payment:{method:'ACH',amount:'$4,820.00'}}}});assert.equal(paid.response.status,200);assert.equal(paid.body.record.status,'paid');assert.equal(paid.body.record.payload.payment.method,'ACH')});
test('approval requests can be opened by users and reviewed by admins',async()=>{const created=await request('/api/companies/cmp_acme/approvals',{method:'POST',body:{kind:'password_access',title:'Request registrar credential',payload:{credential:'Domain registrar'}}});assert.equal(created.response.status,201);assert.equal(created.body.approval.status,'pending');const listed=await request('/api/companies/cmp_acme/approvals',{as:'admin'});assert.equal(listed.response.status,200);assert.ok(listed.body.approvals.some(item=>item.title==='Request registrar credential'))});
test('platform owner can manage portal settings and install profile',async()=>{const denied=await request('/api/internal/settings',{as:'operator',method:'PUT',body:{key:'portal.productName',value:'Northstar',scope:'msp'}});assert.equal(denied.response.status,403);const deniedProfile=await request('/api/internal/install-profile',{as:'operator',method:'PUT',body:{profileName:'Operator attempt',databaseProvider:'postgresql'}});assert.equal(deniedProfile.response.status,403);const saved=await request('/api/internal/settings',{as:'owner',method:'PUT',body:{key:'portal.productName',value:'Northstar',scope:'msp'}});assert.equal(saved.response.status,200);assert.equal(saved.body.setting.key,'portal.productName');const profile=await request('/api/internal/install-profile',{as:'owner'});assert.equal(profile.response.status,200);assert.equal(profile.body.installProfile.databaseProvider,'sqlite');const savedProfile=await request('/api/internal/install-profile',{as:'owner',method:'PUT',body:{profileName:'Production IIS',databaseProvider:'sqlite',deploymentTarget:'iis-reverse-proxy',publicUrl:'https://portal.example.com',options:{backupSchedule:'nightly encrypted backup'}}});assert.equal(savedProfile.response.status,200);assert.equal(savedProfile.body.installProfile.publicUrl,'https://portal.example.com');assert.equal(savedProfile.body.installProfile.options.backupSchedule,'nightly encrypted backup')});
test('client administrators create durable invitations and manage memberships',async()=>{const denied=await request('/api/companies/cmp_acme/people',{method:'POST',body:{name:'Alex Morgan',email:'alex.morgan@acme.example',role:'Member'}});assert.equal(denied.response.status,403);const invited=await request('/api/companies/cmp_acme/people',{as:'admin',method:'POST',body:{name:'Alex Morgan',email:'alex.morgan@acme.example',phone:'(617) 555-0100',department:'Finance',title:'Controller',role:'Billing administrator'}});assert.equal(invited.response.status,201);assert.equal(invited.body.person.membershipStatus,'invited');assert.equal(invited.body.person.role,'client_admin');assert.equal(invited.body.person.department,'Finance');const duplicate=await request('/api/companies/cmp_acme/people',{as:'admin',method:'POST',body:{name:'Alex Morgan',email:'alex.morgan@acme.example',role:'Member'}});assert.equal(duplicate.response.status,409);assert.equal(duplicate.body.error.code,'PERSON_ALREADY_ASSIGNED');const updated=await request(`/api/companies/cmp_acme/people/${invited.body.person.id}`,{as:'admin',method:'PATCH',body:{role:'Member',membershipStatus:'active',phone:'(617) 555-0101'}});assert.equal(updated.response.status,200);assert.equal(updated.body.person.role,'client_user');assert.equal(updated.body.person.membershipStatus,'active');assert.equal(updated.body.person.phone,'(617) 555-0101');const listed=await request('/api/companies/cmp_acme/people',{as:'admin'});assert.ok(listed.body.people.some(person=>person.email==='alex.morgan@acme.example'&&person.role==='client_user'))});
test('the last active company administrator cannot be revoked',async()=>{const{response,body}=await request('/api/companies/cmp_acme/people/usr_acme_admin',{as:'admin',method:'PATCH',body:{membershipStatus:'revoked'}});assert.equal(response.status,409);assert.equal(body.error.code,'LAST_ADMIN_REQUIRED')});
test('company settings use isolated tenant namespaces',async()=>{const acme=await request('/api/internal/settings',{as:'admin',method:'PUT',body:{key:'policy.restrictions.require-mfa',value:{enabled:true,label:'Require MFA',view:'restrictions'},scope:'company',companyId:'cmp_acme'}});assert.equal(acme.response.status,200);const atlas=await request('/api/internal/settings',{as:'owner',method:'PUT',body:{key:'policy.restrictions.require-mfa',value:{enabled:false,label:'Require MFA',view:'restrictions'},scope:'company',companyId:'cmp_atlas'}});assert.equal(atlas.response.status,200);assert.notEqual(acme.body.setting.id,atlas.body.setting.id);const acmeList=await request('/api/internal/settings?companyId=cmp_acme',{as:'owner'});const atlasList=await request('/api/internal/settings?companyId=cmp_atlas',{as:'owner'});assert.equal(acmeList.body.settings.find(setting=>setting.key==='policy.restrictions.require-mfa').value.enabled,true);assert.equal(atlasList.body.settings.find(setting=>setting.key==='policy.restrictions.require-mfa').value.enabled,false)});
test('document records and update approvals are durable and permission scoped',async()=>{const denied=await request('/api/companies/cmp_acme/records',{method:'POST',body:{id:'document-qbr-2026',type:'document',title:'QBR 2026',payload:{category:'Reports'}}});assert.equal(denied.response.status,403);const created=await request('/api/companies/cmp_acme/records',{as:'admin',method:'POST',body:{id:'document-qbr-2026',type:'document',title:'QBR 2026',status:'active',payload:{category:'Reports',file:'PDF - 4.2 MB'}}});assert.equal(created.response.status,201);const updated=await request('/api/companies/cmp_acme/records/document-qbr-2026',{as:'admin',method:'PATCH',body:{payload:{category:'Business reviews',reviewDate:'2026-10-01'}}});assert.equal(updated.response.status,200);assert.equal(updated.body.record.payload.category,'Business reviews');const approval=await request('/api/companies/cmp_acme/approvals',{method:'POST',body:{kind:'document_update',title:'Update QBR 2026',payload:{documentId:'document-qbr-2026'}}});assert.equal(approval.response.status,201);const listed=await request('/api/companies/cmp_acme/approvals',{as:'admin'});assert.ok(listed.body.approvals.some(item=>item.kind==='document_update'&&item.payload.documentId==='document-qbr-2026'))});
test('each signed-in user can persist and reload their own profile preferences',async()=>{const before=await request('/api/profile');assert.equal(before.response.status,200);assert.equal(before.body.profile.identityEmail,'jordan@acme.example');const saved=await request('/api/profile',{method:'PATCH',body:{name:'Jordan T.',email:'jordan.notifications@acme.example',phone:'(617) 555-0198',mobile:'(617) 555-0199',department:'Operations',title:'Operations Coordinator',location:'Boston HQ',timezone:'Eastern Time',manager:'Taylor Morgan',preferredContact:'Portal + email',digest:'Weekly service digest'}});assert.equal(saved.response.status,200);assert.equal(saved.body.profile.name,'Jordan T.');assert.equal(saved.body.profile.email,'jordan.notifications@acme.example');assert.equal(saved.body.profile.identityEmail,'jordan@acme.example');assert.equal(saved.body.profile.department,'Operations');const reloaded=await request('/api/profile');assert.equal(reloaded.body.profile.mobile,'(617) 555-0199');assert.equal(reloaded.body.profile.digest,'Weekly service digest');const admin=await request('/api/profile',{as:'admin'});assert.notEqual(admin.body.profile.email,'jordan.notifications@acme.example')});
test('the shared company master record persists across client and MSP portals',async()=>{const denied=await request('/api/companies/cmp_acme',{method:'PATCH',body:{phone:'(617) 555-0200'}});assert.equal(denied.response.status,403);const saved=await request('/api/companies/cmp_acme',{as:'admin',method:'PATCH',body:{name:'Acme & Co.',address:'100 Main Street, Boston, MA',primaryLocation:'Boston HQ',phone:'(617) 555-0200',website:'https://acme.example',industry:'Professional Services',employees:47,billingEmail:'billing@acme.example'}});assert.equal(saved.response.status,200);assert.equal(saved.body.company.profile.phone,'(617) 555-0200');assert.equal(saved.body.company.profile.employees,47);const visibleToUser=await request('/api/companies/cmp_acme');assert.equal(visibleToUser.response.status,200);assert.equal(visibleToUser.body.company.profile.address,'100 Main Street, Boston, MA');assert.equal(visibleToUser.body.company.profile.billingEmail,'billing@acme.example');const lifecycleDenied=await request('/api/companies/cmp_acme',{as:'admin',method:'PATCH',body:{planName:'Unauthorized plan change'}});assert.equal(lifecycleDenied.response.status,403);const managed=await request('/api/companies/cmp_acme',{as:'owner',method:'PATCH',body:{planName:'Managed Complete Plus',status:'active'}});assert.equal(managed.response.status,200);assert.equal(managed.body.company.planName,'Managed Complete Plus');const crossTenant=await request('/api/companies/cmp_atlas',{as:'admin',method:'PATCH',body:{phone:'nope'}});assert.equal(crossTenant.response.status,404)});
test('approval decisions enforce ownership, administrator review, and terminal state',async()=>{const created=await request('/api/companies/cmp_acme/approvals',{body:{id:'approval-software-license',kind:'software_access',title:'Approve design software',payload:{product:'Design Suite'}} ,method:'POST'});assert.equal(created.response.status,201);const foreign=await request('/api/companies/cmp_acme/approvals',{as:'admin',method:'POST',body:{id:'approval-admin-created',kind:'internal_review',title:'Admin-only review'}});assert.equal(foreign.response.status,201);const userList=await request('/api/companies/cmp_acme/approvals');assert.ok(userList.body.approvals.some(item=>item.id==='approval-software-license'));assert.ok(!userList.body.approvals.some(item=>item.id==='approval-admin-created'));const selfApprove=await request('/api/companies/cmp_acme/approvals/approval-software-license',{method:'PATCH',body:{decision:'approved',reason:'Self approval'}});assert.equal(selfApprove.response.status,403);const missingReason=await request('/api/companies/cmp_acme/approvals/approval-software-license',{as:'admin',method:'PATCH',body:{decision:'approved'}});assert.equal(missingReason.response.status,400);assert.equal(missingReason.body.error.code,'APPROVAL_REASON_REQUIRED');const approved=await request('/api/companies/cmp_acme/approvals/approval-software-license',{as:'admin',method:'PATCH',body:{decision:'approved',reason:'Manager confirmed license and budget'}});assert.equal(approved.response.status,200);assert.equal(approved.body.approval.status,'approved');assert.equal(approved.body.approval.decisionReason,'Manager confirmed license and budget');assert.equal(approved.body.approval.payload.decision.status,'approved');const repeated=await request('/api/companies/cmp_acme/approvals/approval-software-license',{as:'admin',method:'PATCH',body:{decision:'denied',reason:'Changed mind'}});assert.equal(repeated.response.status,409);assert.equal(repeated.body.error.code,'APPROVAL_ALREADY_DECIDED');const cancelledRequest=await request('/api/companies/cmp_acme/approvals',{method:'POST',body:{id:'approval-cancel-me',kind:'general',title:'Withdraw this request'}});assert.equal(cancelledRequest.response.status,201);const cancelled=await request('/api/companies/cmp_acme/approvals/approval-cancel-me',{method:'PATCH',body:{decision:'cancelled'}});assert.equal(cancelled.response.status,200);assert.equal(cancelled.body.approval.status,'cancelled');const crossTenant=await request('/api/companies/cmp_atlas/approvals/approval-software-license',{as:'admin',method:'PATCH',body:{decision:'denied',reason:'No access'}});assert.equal(crossTenant.response.status,404);const audit=await request('/api/internal/audit?companyId=cmp_acme&limit=100',{as:'owner'});assert.ok(audit.body.events.some(event=>event.action==='approval.approved'&&event.resourceId==='approval-software-license'))});
test('MSP onboarding creates a scoped client master with optional client administrator',async()=>{const denied=await request('/api/companies',{as:'admin',method:'POST',body:{name:'Go Live Testing LLC'}});assert.equal(denied.response.status,403);const created=await request('/api/companies',{as:'operator',method:'POST',body:{name:'Go Live Testing LLC',city:'Simi Valley, CA',users:17,mrr:4200,adminName:'Casey Admin',adminEmail:'casey@golive.example'}});assert.equal(created.response.status,201);assert.equal(created.body.company.status,'onboarding');assert.equal(created.body.company.profile.employees,17);const companyId=created.body.company.id;const company=await request(`/api/companies/${companyId}`,{as:'operator'});assert.equal(company.response.status,200);assert.equal(company.body.company.profile.primaryLocation,'Simi Valley, CA');const people=await request(`/api/companies/${companyId}/people`,{as:'operator'});assert.equal(people.response.status,200);assert.equal(people.body.people[0].email,'casey@golive.example');assert.equal(people.body.people[0].membershipStatus,'invited');const userDenied=await request(`/api/companies/${companyId}`,{as:'user'});assert.equal(userDenied.response.status,404);const portfolio=await request('/api/companies',{as:'operator'});assert.ok(portfolio.body.companies.some(company=>company.id===companyId));const audit=await request(`/api/internal/audit?companyId=${companyId}`,{as:'operator'});assert.ok(audit.body.events.some(event=>event.action==='company.onboarded'))});
test('MSP integration configuration and API keys are durable, scoped, and never return key hashes',async()=>{
  const denied=await request('/api/internal/integrations',{as:'admin',method:'PUT',body:{provider:'hudu',name:'Hudu',scope:'Publish approved data to clients',syncInterval:'Hourly'}});
  assert.equal(denied.response.status,403);
  const saved=await request('/api/internal/integrations',{as:'operator',method:'PUT',body:{provider:'hudu',name:'Hudu',scope:'Publish approved data to clients',syncInterval:'Hourly'}});
  assert.equal(saved.response.status,200);assert.equal(saved.body.integration.clientVisible,true);assert.equal(saved.body.integration.configuration.syncInterval,'Hourly');
  const keyDenied=await request('/api/internal/api-keys',{as:'operator',method:'POST',body:{name:'Denied key'}});
  assert.equal(keyDenied.response.status,403);
  const created=await request('/api/internal/api-keys',{as:'owner',method:'POST',body:{name:'Reporting',scope:'metrics:read',expiryDays:30}});
  assert.equal(created.response.status,201);assert.match(created.body.apiKey.secret,/^nsp_/);assert.equal(created.body.apiKey.scopes[0],'metrics:read');
  const listed=await request('/api/internal/api-keys',{as:'owner'});
  assert.equal(listed.response.status,200);const record=listed.body.apiKeys.find(key=>key.id===created.body.apiKey.id);assert.ok(record);assert.equal(Object.hasOwn(record,'secret'),false);
  const revoked=await request(`/api/internal/api-keys/${created.body.apiKey.id}`,{as:'owner',method:'DELETE'});
  assert.equal(revoked.response.status,200);
  const audit=await request('/api/internal/audit?limit=100',{as:'owner'});
  assert.ok(audit.body.events.some(event=>event.action==='api_key.created'&&event.resourceId===created.body.apiKey.id));
});
